import { useParams } from 'react-router-dom';
import { useApi } from '../hooks/useApi';
import { alertsApi } from '../services/api';
import { getAlertById } from '../data/mockAlertDetails';
import AlertHeader from '../components/alert/AlertHeader';
import NetworkInfo from '../components/alert/NetworkInfo';
import RiskPanel from '../components/alert/RiskPanel';
import DetectionReasoning from '../components/alert/DetectionReasoning';
import TechnicalEvidence from '../components/alert/TechnicalEvidence';
import EventTimeline from '../components/alert/EventTimeline';
import RelatedAlerts from '../components/alert/RelatedAlerts';
import AffectedAsset from '../components/alert/AffectedAsset';
import AIExplanation from '../components/alert/AIExplanation';
import ExplainableAI from '../components/alert/ExplainableAI';
import AnalystActions from '../components/alert/AnalystActions';
import AnalystNotes from '../components/alert/AnalystNotes';
import LoadingSpinner from '../components/common/LoadingSpinner';
import ErrorMessage from '../components/common/ErrorMessage';

export default function AlertDetail() {
  const { id } = useParams();

  // Fetch alert from API
  const { data: apiAlert, loading, error, refetch } = useApi(
    () => alertsApi.getAlertById(parseInt(id)),
    [id]
  );

  // Get mock detail data for fields not yet in API
  const mockAlert = getAlertById(parseInt(id));

  // Show loading state
  if (loading && !apiAlert) {
    return (
      <div className="flex items-center justify-center h-full">
        <LoadingSpinner size="lg" message="Loading alert details..." />
      </div>
    );
  }

  // Show error state
  if (error && !apiAlert) {
    return (
      <div className="p-6">
        <ErrorMessage
          message={error}
          onRetry={refetch}
        />
      </div>
    );
  }

  // Show not found if no data
  if (!apiAlert && !mockAlert) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-white mb-2">Alert Not Found</h2>
          <p className="text-gray-400">The requested alert could not be found.</p>
        </div>
      </div>
    );
  }

  // Combine API data with mock detail data
  // Use API for basic fields, mock for detailed investigation fields
  const alert = apiAlert ? {
    id: apiAlert.id,
    threat: apiAlert.threat_class,
    severity: apiAlert.severity,
    confidence: apiAlert.confidence,
    status: apiAlert.status,
    detectedAt: apiAlert.timestamp,
    network: {
      sourceIp: apiAlert.src_ip,
      destinationIp: apiAlert.dst_ip,
      sourcePort: apiAlert.src_port || 'Unknown',
      destinationPort: apiAlert.dst_port,
      protocol: apiAlert.protocol,
      flowId: apiAlert.flow_id,
      duration: mockAlert?.network.duration || '00:00:00',
      totalPackets: mockAlert?.network.totalPackets || 'N/A',
      totalBytes: mockAlert?.network.totalBytes || 'N/A'
    },
    risk: {
      score: apiAlert.risk_score,
      category: mockAlert?.risk.category || 'Network Threat',
      attackVector: mockAlert?.risk.attackVector || 'Network Layer',
      targetedAsset: mockAlert?.risk.targetedAsset || 'Unknown'
    },
    // Use mock data for detailed investigation fields
    // TODO: Move these to database/API in future
    detectionReasoning: mockAlert?.detectionReasoning || {
      summary: 'Threat detected by ML model',
      reasons: ['Anomalous behavior detected in network traffic']
    },
    technicalEvidence: mockAlert?.technicalEvidence || {},
    timeline: mockAlert?.timeline || [],
    relatedAlerts: mockAlert?.relatedAlerts || [],
    affectedAsset: mockAlert?.affectedAsset || {
      hostname: `host-${apiAlert.dst_ip}`,
      ip: apiAlert.dst_ip,
      role: 'Unknown',
      criticality: 'Unknown',
      location: 'Unknown',
      owner: 'Unknown',
      services: []
    },
    aiExplanation: mockAlert?.aiExplanation || {
      confidence: apiAlert.confidence,
      model: 'Random Forest + Isolation Forest',
      analysis: 'This alert was generated based on detected network anomalies.',
      recommendation: 'Review network logs and investigate the source of the anomaly.'
    },
    notes: mockAlert?.notes || [{
      id: 1,
      author: 'System',
      timestamp: new Date(apiAlert.created_at).toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit'
      }),
      note: 'Alert automatically generated by SentinelOneWay detection engine'
    }]
  } : mockAlert;

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
      {/* Alert Header */}
      <AlertHeader alert={alert} />

      {/* Top Row - Network Info, Risk, and Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <NetworkInfo network={alert.network} />
        <RiskPanel risk={alert.risk} confidence={alert.confidence} />
        <AnalystActions alertId={alert.id} currentStatus={alert.status} />
      </div>

      {/* Most Important Section - Why Detected */}
      <DetectionReasoning reasoning={alert.detectionReasoning} />

      {/* Technical Evidence */}
      {Object.keys(alert.technicalEvidence).length > 0 && (
        <TechnicalEvidence evidence={alert.technicalEvidence} />
      )}

      {/* Explainable AI - Full Width */}
      <ExplainableAI alertId={alert.id} />

      {/* Timeline and Related Alerts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {alert.timeline && alert.timeline.length > 0 && (
          <EventTimeline timeline={alert.timeline} />
        )}
        {alert.relatedAlerts && alert.relatedAlerts.length > 0 && (
          <RelatedAlerts alerts={alert.relatedAlerts} />
        )}
      </div>

      {/* Affected Asset and Analyst Notes */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <AffectedAsset asset={alert.affectedAsset} />
        <AnalystNotes notes={alert.notes} />
      </div>
    </div>
  );
}
