/**
 * Live Traffic Page
 * Real-time network flow monitoring
 *
 * Real data sources:
 * - GET /api/metrics/current  (flows/sec, packets/sec, bytes/sec, protocol %)
 * - GET /api/simulation/flows (flow records generated by the simulation engine)
 */
import { useState, useEffect, useCallback } from 'react';
import { Activity, Wifi, WifiOff, RefreshCw, Download, Upload, Database } from 'lucide-react';
import PassiveMonitoringBanner from '../components/common/PassiveMonitoringBanner';
import LoadingSpinner from '../components/common/LoadingSpinner';
import EmptyState from '../components/common/EmptyState';
import { fetchApi } from '../services/api';

export default function LiveTraffic() {
  const [metrics, setMetrics] = useState(null);
  const [flows, setFlows] = useState([]);
  const [flowTotal, setFlowTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [autoRefresh, setAutoRefresh] = useState(true);

  const fetchMetrics = useCallback(async () => {
    try {
      const data = await fetchApi('/api/metrics/current');
      setMetrics(data);
    } catch (err) {
      console.error('Error fetching metrics:', err);
      setError(err.message || 'Failed to load metrics');
    }
  }, []);

  const fetchFlows = useCallback(async () => {
    try {
      const data = await fetchApi('/api/simulation/flows?limit=20');
      setFlows(data.flows || []);
      setFlowTotal(data.total || 0);
    } catch (err) {
      console.error('Error fetching flows:', err);
    }
  }, []);

  useEffect(() => {
    let interval = null;
    const initialLoad = async () => {
      setLoading(true);
      await Promise.all([fetchMetrics(), fetchFlows()]);
      setLoading(false);
    };
    initialLoad();

    if (autoRefresh) {
      interval = setInterval(() => {
        fetchMetrics();
        fetchFlows();
      }, 3000); // Refresh every 3 seconds
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [autoRefresh, fetchMetrics, fetchFlows]);

  const formatBytes = (bytes) => {
    if (bytes == null) return '0 B';
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  const formatProtocol = (protocol) => {
    if (!protocol) return 'Unknown';
    return protocol.toUpperCase();
  };

  if (loading && !metrics) {
    return (
      <div className="p-6">
        <LoadingSpinner message="Loading live traffic data..." />
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white flex items-center gap-3">
            <Activity className="w-8 h-8 text-blue-400" />
            Live Traffic
          </h1>
          <p className="text-gray-400 mt-1">
            Real-time network flow monitoring and analysis
          </p>
        </div>

        {/* Auto-refresh toggle */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => setAutoRefresh(!autoRefresh)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors ${
              autoRefresh
                ? 'bg-green-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
            }`}
          >
            {autoRefresh ? <Wifi className="w-4 h-4" /> : <WifiOff className="w-4 h-4" />}
            {autoRefresh ? 'Live' : 'Paused'}
          </button>
          <button
            onClick={() => {
              fetchMetrics();
              fetchFlows();
            }}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        </div>
      </div>

      {/* Passive Monitoring Banner */}
      <PassiveMonitoringBanner />

      {error && (
        <div className="bg-red-500/10 border border-red-500/40 rounded-lg p-4">
          <p className="text-red-300 text-sm">{error}</p>
        </div>
      )}

      {/* Real-time Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-gray-800 rounded-lg p-4 border border-blue-500/30">
          <div className="flex items-center gap-2 text-blue-400 text-sm mb-2">
            <Activity className="w-4 h-4" />
            <span>Flows/sec</span>
          </div>
          <div className="text-3xl font-bold text-white">
            {metrics?.flows_per_second?.toFixed(1) || '0.0'}
          </div>
          <div className="text-xs text-gray-500 mt-1">
            {metrics?.packets_per_second?.toFixed(0) || '0'} packets/sec
          </div>
        </div>

        <div className="bg-gray-800 rounded-lg p-4 border border-green-500/30">
          <div className="flex items-center gap-2 text-green-400 text-sm mb-2">
            <Download className="w-4 h-4" />
            <span>Bytes/sec</span>
          </div>
          <div className="text-3xl font-bold text-white">
            {formatBytes(metrics?.bytes_per_second || 0)}/s
          </div>
          <div className="text-xs text-gray-500 mt-1">Total throughput (sniffed)</div>
        </div>

        <div className="bg-gray-800 rounded-lg p-4 border border-orange-500/30">
          <div className="flex items-center gap-2 text-orange-400 text-sm mb-2">
            <Upload className="w-4 h-4" />
            <span>Sample Age</span>
          </div>
          <div className="text-3xl font-bold text-white">
            {metrics?.timestamp ? new Date(metrics.timestamp).toLocaleTimeString('en-US', { hour12: false }) : '—'}
          </div>
          <div className="text-xs text-gray-500 mt-1">Latest metric snapshot</div>
        </div>

        <div className="bg-gray-800 rounded-lg p-4 border border-purple-500/30">
          <div className="flex items-center gap-2 text-purple-400 text-sm mb-2">
            <Database className="w-4 h-4" />
            <span>Flows Captured</span>
          </div>
          <div className="text-3xl font-bold text-white">
            {flowTotal.toLocaleString()}
          </div>
          <div className="text-xs text-gray-500 mt-1">From simulation engine</div>
        </div>
      </div>

      {/* Protocol Distribution */}
      <div className="bg-gray-800 rounded-lg p-6 border border-gray-700">
        <h2 className="text-xl font-bold text-white mb-4">Protocol Distribution</h2>
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-gray-900 rounded-lg p-4">
            <div className="text-gray-400 text-sm">TCP</div>
            <div className="text-2xl font-bold text-blue-400 mt-1">
              {metrics?.tcp_percentage?.toFixed(1) || '0'}%
            </div>
          </div>
          <div className="bg-gray-900 rounded-lg p-4">
            <div className="text-gray-400 text-sm">UDP</div>
            <div className="text-2xl font-bold text-green-400 mt-1">
              {metrics?.udp_percentage?.toFixed(1) || '0'}%
            </div>
          </div>
          <div className="bg-gray-900 rounded-lg p-4">
            <div className="text-gray-400 text-sm">DNS</div>
            <div className="text-2xl font-bold text-purple-400 mt-1">
              {metrics?.dns_percentage?.toFixed(1) || '0'}%
            </div>
          </div>
        </div>
      </div>

      {/* Live Flow Table */}
      <div className="bg-gray-800 rounded-lg border border-gray-700 overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-700">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            Recent Network Flows
            {autoRefresh && (
              <span className="flex items-center gap-1 text-sm text-green-400 font-normal">
                <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
                Live
              </span>
            )}
          </h2>
        </div>

        {flows.length === 0 ? (
          <div className="p-6">
            <EmptyState
              type="alerts"
              title="No Flow Records Yet"
              description="Flows appear here when the simulation engine generates traffic. Start a scenario in the Simulation Lab to populate this table."
            />
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-900">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Source IP
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Destination IP
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Ports
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Protocol
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Packets
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">
                    Bytes
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-700">
                {flows.map((flow) => (
                  <tr key={flow.flow_id || flow.timestamp} className="hover:bg-gray-700/50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                      {flow.src_ip}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                      {flow.dst_ip}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-400">
                      {flow.src_port} → {flow.dst_port}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        formatProtocol(flow.protocol).startsWith('TCP') ? 'bg-blue-500/20 text-blue-400' :
                        formatProtocol(flow.protocol).startsWith('UDP') ? 'bg-green-500/20 text-green-400' :
                        'bg-purple-500/20 text-purple-400'
                      }`}>
                        {formatProtocol(flow.protocol)}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                      {(flow.packet_count || 0).toLocaleString()}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                      {formatBytes(flow.byte_count || 0)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Info Banner */}
      <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
        <p className="text-blue-300 text-sm">
          <strong>Note:</strong> This page displays real-time network flow metadata.
          SentinelOneWay operates in passive monitoring mode - no traffic is blocked or modified.
        </p>
      </div>
    </div>
  );
}